name: flutter_secure_storage
description: Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
version: 4.2.0
homepage: https://github.com/mogol/flutter_secure_storage
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.3"

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        pluginClass: FlutterSecureStoragePlugin

dependencies:
  meta: ^1.3.0
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    path: ../flutter_secure_storage_platform_interface

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
