name: flutter_secure_storage
description: Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
version: 4.2.1
homepage: https://github.com/mogol/flutter_secure_storage
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        pluginClass: FlutterSecureStoragePlugin
      linux:
        default_package: flutter_secure_storage_linux
      macos:
        default_package: flutter_secure_storage_macos
      web:
        default_package: flutter_secure_storage_web
      windows:
        default_package: flutter_secure_storage_windows

dependencies:
  meta: ^1.3.0
  flutter:
    sdk: flutter
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # implementation constraints as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # https://github.com/flutter/flutter/issues/46264
#  flutter_secure_storage_linux: ^1.0.0
#  flutter_secure_storage_macos: ^1.0.0
#  flutter_secure_storage_platform_interface: ^1.0.0
#  flutter_secure_storage_web: ^1.0.0
#  flutter_secure_storage_windows: ^1.0.0

  flutter_secure_storage_linux:
    path: ../flutter_secure_storage_linux
  flutter_secure_storage_macos:
    path: ../flutter_secure_storage_macos
  flutter_secure_storage_platform_interface:
    path: ../flutter_secure_storage_platform_interface
  flutter_secure_storage_web:
    path: ../flutter_secure_storage_web
  flutter_secure_storage_windows:
    path: ../flutter_secure_storage_windows

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
