name: flutter_secure_storage_web
description: Web implementation of flutter_secure_storage
version: 1.0.0
homepage: https://github.com/mogol/flutter_secure_storage

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    path: ../flutter_secure_storage_platform_interface

dev_dependencies:
  effective_dart: ^1.3.2

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
