name: flutter_secure_storage_web
description: Web implementation of Flutter Secure Storage.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    path: ../flutter_secure_storage_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
