name: flutter_secure_storage_platform_interface
description: A common platform interface for the flutter_secure_storage plugin.
version: 1.0.0
homepage: https://github.com/mogol/flutter_secure_storage

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12