name: code analysis & formatting

on: [push, pull_request]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v1
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./flutter_secure_storage
      - name: Linter
        run: flutter analyze
        working-directory: ./flutter_secure_storage
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v1
      - name: Format
        run: flutter format -n --set-exit-if-changed .
        working-directory: ./flutter_secure_storage
